import os
os.system('cls')

print("-"*45)
print("Seja bem vindo a calculadora de função afim")
print("-"*45)
print("1 - Descobrir qual será a função")
print("2 - Descobrir o valor de y")
print("3 - Descobrir o valor de a e b")
print("4 - Descobrir o valor da raiz")
print("-"*45)

opcao = input("Digite o número das opções escolhidas: ")

if opcao == "1":
    os.system('cls')
    print("-"*45)
    valordea = int(input("Digite o valor de A: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    valordex = int(input("Digite o valor de X: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    valordeb = int(input("Digite o valor de B: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    print(f"A = {valordea}, X = {valordex}, B = {valordeb}")
    print(f"A função no caso é: f({valordex}) = {valordea}x{valordex} + {valordeb}")
    print("-"*45)
    if valordea == 0:
        print("Ela é Função constante")
    elif valordea == 1 and valordeb == 0:
        print("Ela é função identidade")
    elif valordeb == 0:
        print("Ela é função linear")
    else:
        print("Ela é função afim normal")
    print("-"*45)
elif opcao == "2":
    os.system('cls')
    print("-"*45)
    valordea = int(input("Digite o valor de A: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    valordex = int(input("Digite o valor de X: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    valordeb = int(input("Digite o valor de B: "))
    print("-"*45)
    os.system('cls')
    print("-"*45)
    print(f"A = {valordea}, X = {valordex}, B = {valordeb}")
    print(f"A função no caso é: f({valordex}) = {valordea}x{valordex} + {valordeb}")
    print("-"*45)
    funcao = valordea * valordex + valordeb
    print(f"f({valordex}) = {funcao}")
elif opcao == "3":
    os.system('cls')
    print("-"*45)
    valordex = int(input("Digite o valor de X: "))
    os.system('cls')
    print("-"*45)
    valordey = int(input("Digite o valor de Y: "))
    os.system('cls')
    print("-"*45)
    print(f"Y = {valordey}, X = {valordex}")
    print(f"A função no caso é: f({valordex}) = {valordea}x{valordex} + {valordeb}")
    print("-"*45)

